# Generated by Django 2.1.1 on 2018-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('nb_visites', models.IntegerField(default=1)),
                ('temps_vue', models.IntegerField()),
            ],
        ),
    ]
