# Generated by Django 2.1.1 on 2018-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='temps_vue',
            field=models.IntegerField(default=1),
        ),
    ]
