# Generated by Django 2.1.1 on 2018-10-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0002_auto_20181022_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='titre1', max_length=40),
            preserve_default=False,
        ),
    ]
