# Generated by Django 2.1.1 on 2018-10-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0004_article_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auteur',
        ),
        migrations.AddField(
            model_name='article',
            name='auteur_blog',
            field=models.CharField(default=1, max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='auteur_livre',
            field=models.CharField(default=1, max_length=42),
            preserve_default=False,
        ),
    ]
