# Generated by Django 2.1.1 on 2018-10-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0006_auto_20181029_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_contenu',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_resume',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
