# Generated by Django 2.1.1 on 2018-11-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0011_auto_20181108_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='', max_length=200, upload_to='pictures/'),
        ),
    ]
