# Generated by Django 2.1.1 on 2018-11-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0012_auto_20181108_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='pictures/blank.png', max_length=200, upload_to='pictures/'),
        ),
    ]
