# Generated by Django 2.1.1 on 2018-11-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0017_auto_20181115_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsection',
            options={'ordering': ['-date'], 'verbose_name': 'comment'},
        ),
        migrations.AddField(
            model_name='commentsection',
            name='modification',
            field=models.BooleanField(default=False),
        ),
    ]
