# Generated by Django 2.1.1 on 2018-11-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0021_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default='blanck.png', max_length=200, upload_to='pictures/'),
        ),
    ]
