# Generated by Django 2.1.1 on 2018-11-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0022_auto_20181120_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_litteraire', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sous_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_genre_litteraire', models.CharField(max_length=30)),
                ('genre_litteraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_livreSF.Genre')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='post_genre', to='blog_livreSF.Genre'),
        ),
    ]
