# Generated by Django 2.1.1 on 2018-11-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0023_auto_20181121_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sous_genre',
            field=models.ManyToManyField(blank=True, related_name='post_genre', to='blog_livreSF.Sous_Genre'),
        ),
    ]
