# Generated by Django 2.1.1 on 2018-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0026_auto_20181128_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='auteur_comment',
            field=models.CharField(max_length=42),
        ),
    ]
