# Generated by Django 2.1.1 on 2018-11-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0028_auto_20181128_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='comment',
            field=models.TextField(),
        ),
    ]
