# Generated by Django 2.1.1 on 2018-12-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0029_auto_20181201_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='number_words',
            field=models.IntegerField(default=0),
        ),
    ]
