# Generated by Django 2.1.1 on 2018-12-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0030_commentsection_number_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='nombre_mots_afficher',
            field=models.IntegerField(default=0),
        ),
    ]
