# Generated by Django 2.1.1 on 2018-12-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0032_remove_commentsection_number_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='number_words',
            field=models.IntegerField(default=0),
        ),
    ]
