# Generated by Django 2.1.1 on 2018-12-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livreSF', '0033_commentsection_number_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sous_genre',
            name='genre_litteraire',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sous_genre',
        ),
        migrations.DeleteModel(
            name='Sous_Genre',
        ),
    ]
