# Generated by Django 2.1.1 on 2018-11-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0006_auto_20181113_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prenom',
            field=models.CharField(blank=True, default='jeanmimi', max_length=30),
        ),
    ]
