# Generated by Django 2.1.1 on 2018-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0007_auto_20181114_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
