# Generated by Django 2.1.1 on 2018-11-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0008_auto_20181120_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='avatars/'),
        ),
    ]
