# Generated by Django 2.1.1 on 2018-11-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0009_auto_20181121_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='pseudo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prenom',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
