# Generated by Django 2.1.1 on 2018-11-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0011_auto_20181125_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nombre_post_ecrit',
            field=models.IntegerField(default=0),
        ),
    ]
