# Generated by Django 2.1.1 on 2018-11-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0012_profile_nombre_post_ecrit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rang',
            field=models.CharField(default='Petite larve en devenir', max_length=50),
        ),
    ]
