# Generated by Django 2.1.1 on 2018-11-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0013_profile_rang'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug_pseudo',
            field=models.SlugField(default='def', max_length=40),
            preserve_default=False,
        ),
    ]
