# Generated by Django 2.1.1 on 2018-11-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0016_auto_20181128_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/anonymous_image.png', max_length=200, upload_to='avatars/'),
        ),
    ]
