# Generated by Django 2.1.1 on 2018-12-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0018_auto_20181201_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='objet_message',
            field=models.CharField(default='rien', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
