# Generated by Django 2.1.1 on 2018-12-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0020_mailbox_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbox',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='mailbox',
            name='message_lu',
            field=models.BooleanField(default=False),
        ),
    ]
