# Generated by Django 2.1.2 on 2018-12-21 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NouvelleEcrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Attention le titre ne doit pas excéder 100 caractères ', max_length=100)),
                ('contenu', models.TextField(default='', help_text="Ecriture en markdown possible afin de structurer et d'accéder à des fonctionnalités d'HTML")),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('slug', models.SlugField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modification', models.BooleanField(default=False)),
                ('information_additionnelle', models.TextField(blank=True, default='', help_text="Ecriture en markdown possible afin de structurer et d'accéder à des fonctionnalités d'HTML")),
                ('auteur_nouvelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='nouvelle_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nouvelle',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='nouvelleecrite',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text="N'hésitez pas à prendre un peu de temps pour spécifier quelques tags. C'est très pratique pour aiguiller le lecteur :) Si jamais le tag voulu n'apparait pas ici, vous pouvez en ajouter un en bas de ce formulaire ", related_name='post_tag', to='nouvelle.Tag'),
        ),
    ]
