# Generated by Django 2.1.2 on 2018-12-22 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nouvelle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('modification', models.BooleanField(default=False)),
                ('number_words', models.IntegerField(default=0)),
                ('nombre_mots_afficher', models.IntegerField(default=0)),
                ('auteur_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nouvelle_auteur_comment', to=settings.AUTH_USER_MODEL)),
                ('nouvelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouvelle.NouvelleEcrite')),
            ],
            options={
                'verbose_name': 'comment',
                'ordering': ['-date'],
            },
        ),
    ]
