# Generated by Django 2.1.1 on 2018-12-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouvelle', '0002_commentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nouvelleecrite',
            name='information_additionnelle',
            field=models.TextField(blank=True, default='', help_text='Ici vous pouvez ajouter des informations complémentaire telles que ds explications, des indices, des inspirations que vous avez eu, des références, ... en somme tout ce que vous voulez ! Cette partie sera cachée et dévoilée que si le lecteur en fait la demande.'),
        ),
    ]
